alphagov/mapit

conf/ci.yml
jenkins.sh
jenkins_branches.sh
mapit/tests/test_import_commands.py
project/settings.py

For: https://trello.com/c/i0DJVKw9/134-mapit-ci-builds
Lots of moving pieces here, including changes to ci-puppet, ci-deploy, and the jenkins jobs for mapit themselves.  Once we start seeing green ticks on these commits we'll be in a position to properly review the commits and merge.

Provide CI builds

---

import-db-from-s3.sh

Updated the import script to use the May 2016 data

Update import script to point to latest db dump

---

import-db-from-s3.sh

We have new ONSPD data from ONS. This was updated [here](https://github.gds/gds/mapit-scripts/pull/11).
This script change now points to the new data dump containing all the new changes.
This dump contains:
ONSPD August 2016 (new) `20160831-ONSPD_AUG_2016_UK.zip`
Boundary lines May 2016 `20160831-bdline_gb-2016-05.zip`
ONSNI December 2015 `20160902-osni-dec-2015.tar.gz`
These are the most up to date data available as of this date.
[Trello card](https://trello.com/c/JwqUB8gz/482-onspd-update-2)

Update import script from S3

---

import-db-from-s3.sh

This script now points to the new data dump containg the latest BoundaryLine (October 2016 2nd release)  and ONSPD (November 2016) data.
[Trello card](https://trello.com/c/VtvHkXvn/547-import-october-boundary-line-postcode-data-into-mapit-2)

Update import db from S3 script

---

Jenkinsfile
import-db-from-s3.sh

There has been no change to the boundary data here as this only updates every
6 months.

Reference new db including Feb 2017 ONSPD

---

Jenkinsfile

This helps us with rate limiting issues and leaves workspaces tidy.

Check out using SSH and clean up afterwards

---

requirements.txt

This includes some security fixes - see the release notes for details:
https://docs.djangoproject.com/en/dev/releases/1.8.18/

Upgrade Django to 1.8.18

---

import-db-from-s3.sh

We have a new database export file which can be used for updating Mapit with the latest boundary and postcode data.
[Trello card](https://trello.com/c/wjzmv1f6/141-next-mapit-update-for-postcode-and-boundary-data)

Update Mapit import from S3 file location

---

IMPORTING-DATA.md
README.md
mapit_gb/management/commands/mapit_UK_add_missing_codes.py

We've moved mapit-scripts to GitHub so need to update our docs.

Mapit-scripts has moved

---

import-db-from-s3.sh

We've generated a new database with the August 2017 ONSPD database.  This
script enables us to import it to the production MapIt servers.
The database was generated using the script updated in https://github.com/alphagov/mapit-scripts/pull/1
https://trello.com/c/8O0U827j/161-update-postcode-data-in-mapit

Update import script with new DB

---

Jenkinsfile

This is clearer and more specific that deploying the branch.

Deploy the release tag to integration

---

IMPORTING-DATA.md
README.md

Also done some tidying up of the markdown so it renders correctly on GitHub
https://trello.com/c/dql5PCnX/283-update-mapit-data

Update docs following recent data import

---

import-db-from-s3.sh

Data has been updated again to include correct slug for Folkestone & Hythe council.
https://trello.com/c/dql5PCnX/283-update-mapit-data

Update S3 location and checksum

---

import-db-from-s3.sh

This PR is to update the S3 bucket location and hash for the latest data dump

Updates location of new data and hash

---

import-db-from-s3.sh

I've just uploaded this version to S3 following on from the latest import after boundary changes.
[Trello Card](https://trello.com/c/g6GfxrJk/987-update-mapit-to-include-changes-in-organisation)

Update database dump URL to latest version

---

import-db-from-s3.sh

I misunderstood the command and updated the database name in the
wrong place, it should stay as `mapit.sql.gz` here.

Update database name

---

IMPORTING-DATA.md

A update to the documentation having just gone through the steps
to update our Mapit data. It includes:
- fixing broken links
- breaking down some of the process into steps to make it easier to
follow
- adding a troubleshooting section with some of the issues I had

Update Importing data doc

---

mapit/management/command_utils.py
mapit/tests/test_doctests.py
mapit_gb/management/commands/mapit_UK_fix_2019-05-2.py
mapit_gb/management/commands/mapit_UK_fix_2019-05.py

This keeps us up to date with the latest upstream changes.

Merge upstream commits

---

project/settings.py

Same as we do with other env variables
https://trello.com/c/QXBhaFlh/1449-5-add-mapit-to-govuk-docker

Get MAPIT_DB_PASS from env or config

---

IMPORTING-DATA.md

This updates the command needed to import data from s3 within Mapit using Docker.
Trello: https://trello.com/c/6ss0MKQw/1783-8-import-new-mapit-data-using-docker

Update step 6 in importing data readme

---

mapit_gb/management/commands/mapit_UK_add_2020_structural_changes.py

This merges in the upstream changes, so we can run the script for recent boundary changes: 184473f.

Merge upstream

---

ABOUT-DATASETS.md
IMPORTING-DATA.md
README.md
TESTING-SERVER.md
mapit_gb/management/commands/mapit_UK_add_override_names_to_local_authorities.py
mapit_gb/management/commands/mapit_UK_add_slugs_to_local_authorities.py

During our recent attempt at importing data, we found some areas of improvement in some of the scripts
as well as in the documentation. See individual commit messages for more detail.
Trello card: https://trello.com/c/iBQQVCNM/2206-improve-mapit-documentation-and-import-scripts

Improve data import process

---

IMPORTING-DATA.md
TESTING-SERVER.md

Follow up of https://github.com/alphagov/mapit/pull/109
Trello card: https://trello.com/c/iBQQVCNM/2206-improve-mapit-documentation-and-import-scripts

Fix anchor links in documentation

---

import-db-from-s3.sh

Includes October 2020 Boundary Line and November 2020  ONSPD updates.
We have tested the new database on staging.
Trello card: https://trello.com/c/afMgfqo2/2036-8-import-latest-mapit-data-using-docker

Update S3 location and checksum of Mapit db

---

mapit/iterables.py
mapit/templates/mapit/footer.html
mapit_it/templates/mapit/footer.html

This brings us up to date with changes before Mysociety introduces Github actions (PR to follow) 
Trello card: https://trello.com/c/rm2WTeqk/2331-pull-upstream-changes-from-mysociety

Pull changes upstream

---

docs/importing-data.md

The link no longer provides useful results

Removes unhelpful link to ONS postcode data

---

.github/workflows/default.yml
bin/mapit_make_css
conf/general.yml-example
mapit/context_processors.py
mapit/geometryserialiser.py
mapit/management/commands/mapit_delete_areas_from_new_generation.py
mapit/management/commands/mapit_generation_activate.py
mapit/management/commands/mapit_generation_create.py
mapit/management/commands/mapit_generation_deactivate.py
mapit/templates/mapit/api/point.html
mapit/tests/test_generation_commands.py
mapit/tests/test_views.py
mapit/views/areas.py
mapit_gb/controls/2021-05.py
mapit_gb/data/authorities.json
mapit_gb/fixtures/uk.json
mapit_gb/management/commands/mapit_UK_add_2020_structural_changes.py
mapit_gb/management/commands/mapit_UK_add_2021_structural_changes.py
mapit_gb/management/commands/mapit_UK_add_missing_codes.py
mapit_gb/management/commands/mapit_UK_import_boundary_line.py
mapit_gb/management/structural_changes.py
mapit_gb/templates/mapit/api/areas-types.html
mapit_gb/templates/mapit/api/postcode-example.html
project/settings.py
setup.py
tox.ini

Brings upstream changes into our fork.
Trello card: https://trello.com/c/IwakiikF

Update Mapit for May 2021

---

import-db-from-s3.sh

This is only to be merged when we are ready to release the May 2021 update.
Trello card: https://trello.com/c/IwakiikF

Update import URL and SHA for May 2021 update

---

docs/importing-data.md

These instructions weren't particularly clear, missed some steps and had some steps in the wrong order.
Removing most of the words and replacing with step-by-step commands/links, fixing broken links and adding some clarifications where things weren't clear.
Trello card: https://trello.com/c/IwakiikF

Update instructions for testing on staging
